// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOlxCuHHqx3uTDlUCDN1R1FiOBZVxTJRg',
    appId: '1:956244832711:web:f0ecf27747d901773b69e2',
    messagingSenderId: '956244832711',
    projectId: 'tomin-1',
    authDomain: 'tomin-1.firebaseapp.com',
    storageBucket: 'tomin-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgRJ2VSQRcmrxFJaoaD-8Sm0MTIvM01Q',
    appId: '1:956244832711:android:b9458d72947568d83b69e2',
    messagingSenderId: '956244832711',
    projectId: 'tomin-1',
    storageBucket: 'tomin-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbsXnWn0kWRY-pBXLWYlpuysLB3zZTyw',
    appId: '1:956244832711:ios:b389aeb77ad9cc3c3b69e2',
    messagingSenderId: '956244832711',
    projectId: 'tomin-1',
    storageBucket: 'tomin-1.firebasestorage.app',
    iosBundleId: 'com.d3tl4.santafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSbsXnWn0kWRY-pBXLWYlpuysLB3zZTyw',
    appId: '1:956244832711:ios:b389aeb77ad9cc3c3b69e2',
    messagingSenderId: '956244832711',
    projectId: 'tomin-1',
    storageBucket: 'tomin-1.firebasestorage.app',
    iosBundleId: 'com.d3tl4.santafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOlxCuHHqx3uTDlUCDN1R1FiOBZVxTJRg',
    appId: '1:956244832711:web:7c110dd647be387a3b69e2',
    messagingSenderId: '956244832711',
    projectId: 'tomin-1',
    authDomain: 'tomin-1.firebaseapp.com',
    storageBucket: 'tomin-1.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBOlxCuHHqx3uTDlUCDN1R1FiOBZVxTJRg',
    appId: '1:956244832711:web:7c110dd647be387a3b69e2',
    messagingSenderId: '956244832711',
    projectId: 'tomin-1',
    authDomain: 'tomin-1.firebaseapp.com',
    storageBucket: 'tomin-1.firebasestorage.app',
  );
}
